### PR TITLE
feat: check generic types to allow usage in lists

### PR DESCRIPTION
**Pull request by simonkellly**

### CODE REVIEW

**Comment by Thundernerd** [comment]
@simonkellly could you please provide an example in which this works? I cannot find a situation where this applies, but I'm sure there is one.

**Comment by simonkellly** [comment]
`public List<SerialzableInteface<IInterface>> MyInterfaces;`

in this case, the type of the field is generic, so it gets checked if the generic type is serializable interface. As it is a list, it would not be true, and the type being checked would become the list's base type, eventually making the generic type null for the property drawer.

This way, the generic argument is checked to see if it is a serialiizableinterface, and as such set the generic type properly

**Comment by Thundernerd** [comment]
I did a quick test using your code, but it doesn't seem to work properly. If you change the value of one element it'll change them all.
image

**Comment by simonkellly** [comment]
You are right, it wasn't resetting the active drawer when rendering each different element so this should now be fixed

**Comment by simonkellly** [comment]
Did that fix work for you?

**Comment by AlexejheroYTB** [comment]
The fix in this pull request seems to be working correctly. Previously I was using lists of serializable structs which had serializable interface fields on them to bypass this 😆

**Comment by Thundernerd** [comment]
Apologies for the delay, I'll get back to you ASAP on this :).

**Comment by AlexejheroYTB** [comment]
Any updates on this pull request?

**Comment by Thundernerd** [comment]
Gonna close this one since I've added it manually because I wanted to change the code slightly :)

**Pull request closed without merging**
